#!/bin/bash
set -euo pipefail

# Script to generate 02-area-generated.sql with embedded shapefile data
# Converts ZIP files from database/init/shapefiles/ to hex-encoded bytea values

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHAPEFILE_DIR="${SCRIPT_DIR}/shapefiles"
OUTPUT_FILE="${SCRIPT_DIR}/02-area-generated.sql"

# Check if shapefiles directory exists
if [ ! -d "${SHAPEFILE_DIR}" ]; then
    echo "ERROR: Shapefiles directory not found: ${SHAPEFILE_DIR}" >&2
    exit 1
fi

# Function to convert a file to hex-encoded SQL bytea
# Args: $1 = file path
# Returns: PostgreSQL decode() statement for the hex data
encode_file_to_hex() {
    local file_path="$1"

    if [ ! -f "${file_path}" ]; then
        echo "ERROR: File not found: ${file_path}" >&2
        exit 1
    fi

    # Convert file to hex using xxd
    # -p: plain hexdump (no line numbers, no ASCII)
    # -c 0: output continuous hex string (no line breaks)
    local hex_data
    hex_data=$(xxd -p -c 0 "${file_path}")

    # Return PostgreSQL decode function
    echo "decode('${hex_data}', 'hex')::bytea"
}

# Define area
# Format: "competent_authority_area_id|filename|zipfile|competent_authority_id|comment"
declare -a AREAS=(
    "amsterdam-area-0363|Amsterdam-dummy.zip|Amsterdam-dummy.zip|sdep-ca-0363|Amsterdam area"
    "rotterdam-area-0599|Rotterdam.zip|Rotterdam.zip|sdep-ca-0599|Rotterdam area"
    "denhaag-area-0518|Den-Haag.zip|Den-Haag-dummy.zip|sdep-ca-0518|Den Haag area"
    "amstelveen-area-0362|Amstelveen.zip|Amstelveen-dummy.zip|sdep-ca-0362|Amstelveen area"
    "bergen-area-0373|Bergen.zip|Bergen-dummy.zip|sdep-ca-0373|Bergen (Noord-Holland) area"
    "delft-area-0503|Delft.zip|Delft.zip|sdep-ca-0503|Delft area"
    "diemen-area-0384|Diemen.zip|Diemen.zip|sdep-ca-0384|Diemen area"
    "gouda-area-0513|Gouda.zip|Gouda.zip|sdep-ca-0513|Gouda area"
    "groningen-area-0014|Groningen.zip|Groningen.zip|sdep-ca-0014|Groningen area"
    "haarlem-area-0392|Haarlem.zip|Haarlem.zip|sdep-ca-0392|Haarlem area"
    "katwijk-area-0537|Katwijk.zip|Katwijk.zip|sdep-ca-0537|Katwijk area"
    "landsmeer-area-0415|Landsmeer.zip|Landsmeer.zip|sdep-ca-0415|Landsmeer area"
    "leiden-area-0546|Leiden.zip|Leiden.zip|sdep-ca-0546|Leiden area"
    "maastricht-area-0935|Maastricht.zip|Maastricht.zip|sdep-ca-0935|Maastricht area"
    "middelburg-area-0687|Middelburg.zip|Middelburg.zip|sdep-ca-0687|Middelburg area"
    "noordwijk-area-0575|Noordwijk.zip|Noordwijk.zip|sdep-ca-0575|Noordwijk area"
    "pijnackernootdorp-area-1926|Pijnacker-Nootdorp-dummy.zip|Pijnacker-Nootdorp-dummy.zip|sdep-ca-1926|Pijnacker-Nootdorp area"
    "renkum-area-0274|Renkum.zip|Renkum.zip|sdep-ca-0274|Renkum area"
    "sluis-area-1714|Sluis.zip|Sluis.zip|sdep-ca-1714|Sluis area"
    "schouwenduiveland-area-1676|Schouwen-Duiveland.zip|Schouwen-Duiveland.zip|sdep-ca-1676|Schouwen-Duiveland area"
    "texel-area-0448|Texel.zip|Texel.zip|sdep-ca-0448|Texel area"
    "utrecht-area-0344|Utrecht.zip|Utrecht.zip|sdep-ca-0344|Utrecht area"
    "vlissingen-area-0718|Vlissingen.zip|Vlissingen.zip|sdep-ca-0718|Vlissingen area"
    "voorschoten-area-0626|Voorschoten-dummy.zip|Voorschoten-dummy.zip|sdep-ca-0626|Voorschoten area"
    "waterland-area-0852|Waterland.zip|Waterland.zip|sdep-ca-0852|Waterland area"
    "zaanstad-area-0479|Zaanstad.zip|Zaanstad.zip|sdep-ca-0479|Zaanstad area"
    "zandvoort-area-0473|Zandvoort.zip|Zandvoort.zip|sdep-ca-0473|Zandvoort area"
    "zwolle-area-0193|Zwolle.zip|Zwolle.zip|sdep-ca-0193|Zwolle area"
)

# Start writing the SQL file
cat > "${OUTPUT_FILE}" <<'EOF'
-- Insert areas with embedded shapefile data
--
-- WARNING: This file is auto-generated by generate-area-sql.sh
-- DO NOT EDIT THIS FILE MANUALLY!
--
-- To regenerate this file with updated shapefile data, run:
--   ./database/init/generate-area-sql.sh
--
-- The shapefile ZIP files are hex-encoded and embedded directly in this SQL file.
-- This approach works in all environments without requiring volume mounts or superuser privileges.

EOF

# Generate SQL for each area
for area_def in "${AREAS[@]}"; do
    IFS='|' read -r competent_authority_area_id filename zipfile ca_id comment <<< "${area_def}"

    zipfile_path="${SHAPEFILE_DIR}/${zipfile}"

    echo "Processing ${comment} (${zipfile})..."

    # Check if the ZIP file exists
    if [ ! -f "${zipfile_path}" ]; then
        echo "ERROR: Shapefile not found: ${zipfile_path}" >&2
        echo "ERROR: Cannot generate SQL without all shapefiles." >&2
        exit 1
    fi

    # Get hex-encoded data
    hex_bytea=$(encode_file_to_hex "${zipfile_path}")

    # Generate a proper RFC 9562 UUID for the area_id (functional ID)
    area_uuid=$(python3 -c "import uuid; print(str(uuid.uuid4()))")

    # Extract area name from comment (e.g., "Amsterdam area" -> "Amsterdam")
    area_name=$(echo "${comment}" | sed 's/ area$//')

    # Write SQL INSERT statement
    cat >> "${OUTPUT_FILE}" <<EOF
-- ${comment}
INSERT INTO area (competent_authority_id, area_id, area_name, filename, filedata, created_at)
VALUES (
  (SELECT id FROM competent_authority WHERE competent_authority_id = '${ca_id}'),
  '${area_uuid}',
  '${area_name}',
  '${filename}',
  ${hex_bytea},
  '2025-01-01 00:00:00+00'::timestamptz
);

EOF
done

echo ""
echo "✓ Successfully generated ${OUTPUT_FILE}"
echo "✓ Processed ${#AREAS[@]} areas with embedded shapefile data"
echo ""
echo "The SQL file now contains hex-encoded shapefile data and is ready for database initialization."
