variables:
  APP: sdep-backend
  IMAGE: ${HARBOR_REG}/${HARBOR_REPO}/${APP}
  TAG_LATEST: "latest"

check backend:
  stage: quality
  script:
    - cd backend
    - make install
    - make format
    # - make typecheck
