default:
 interruptible: true

variables:
  APP: sdep-backend
  IMAGE: ${HARBOR_REG}/${HARBOR_REPO}/${APP}
  TAG_LATEST: "latest"

# typecheck:
#   stage: typecheck
#   script:
#     - cd backend
#     - make install
#     - make typecheck

set-tag:
  stage: build
  script:
    # Use "git tag" value (0.1.date, 0.1.0, ...), otherwise use "latest.commit_short_sha"
    - echo "TAG_COMMIT=${CI_COMMIT_TAG:-latest.${CI_COMMIT_SHORT_SHA}}" | tee -a build.env
  artifacts:
    reports:
      dotenv: build.env

build backend:
  stage: build
  needs:
    - job: set-tag
      artifacts: true
  image:
    name: harbor-gn2.cicd.s15m.nl/gcr-io-proxy/kaniko-project/executor:v1.24.0-debug
    entrypoint: [""]
  script:
    # Authenticate
    - echo "${DOCKER_AUTH_CONFIG}" > /kaniko/.docker/config.json # From GitLab group variable (daily rotated)

    # Build
    - cd backend
    - /kaniko/executor
      --context .
      --dockerfile Dockerfile
      --destination ${IMAGE}:${TAG_LATEST}
      --build-arg IMAGE_TAG=${TAG_COMMIT}
      --digest-file=digest.txt
      --cache=false

trigger-deployment-tst:
  stage: build
  needs:
    - job: build backend
    - job: set-tag
      artifacts: true
  # Trigger downstream
  trigger:
    project: ictu/devops/single-digital-entrypoint/sdep-deployment
    strategy: depend
  # Pass to downstream
  variables:
    TAG: ${TAG_COMMIT}
    TAG_BACKEND: "true"
  rules:
    - if: $CI_COMMIT_TAG # Run when tagged
      when: always
    - if: $CI_PIPELINE_SOURCE == "web" # Run when manual
      when: always
    - when: never # Do not run otherwise
